# Generated by Django 5.0.3 on 2024-06-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='text_images/'),
        ),
    ]
