# Generated by Django 5.0.3 on 2024-06-19 01:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_text_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
